// Code generated by goctl-sdk. DO NOT EDIT.

package levee

import (
	"context"
	"fmt"
	"net/url"
	"strconv"
	"strings"
)


// EventsResource provides access to events resources.
type EventsResource struct {
	client *Client
}



// TrackEvent 
func (r *EventsResource) TrackEvent(ctx context.Context, request *EventRequest) (*Response, error) {
	var result Response
	err := r.client.request(
		ctx,
		"POST",
		"/sdk/v1/events",
		nil,
		request,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// FunnelsResource provides access to funnels resources.
type FunnelsResource struct {
	client *Client
}



// GetFunnelStep 
func (r *FunnelsResource) GetFunnelStep(ctx context.Context, slug string) (*FunnelStepInfo, error) {
	path := fmt.Sprintf("/sdk/v1/funnels/%s", slug)
	var result FunnelStepInfo
	err := r.client.request(
		ctx,
		"GET",
		path,
		nil,
		nil,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// OrdersResource provides access to orders resources.
type OrdersResource struct {
	client *Client
}



// CreateOrder 
func (r *OrdersResource) CreateOrder(ctx context.Context, request *OrderRequest) (*OrderResponse, error) {
	var result OrderResponse
	err := r.client.request(
		ctx,
		"POST",
		"/sdk/v1/orders",
		nil,
		request,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// ProductsResource provides access to products resources.
type ProductsResource struct {
	client *Client
}



// GetProduct 
func (r *ProductsResource) GetProduct(ctx context.Context, slug string) (*BillingProductInfo, error) {
	path := fmt.Sprintf("/sdk/v1/products/%s", slug)
	var result BillingProductInfo
	err := r.client.request(
		ctx,
		"GET",
		path,
		nil,
		nil,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// QuizzesResource provides access to quizzes resources.
type QuizzesResource struct {
	client *Client
}



// GetQuiz 
func (r *QuizzesResource) GetQuiz(ctx context.Context, slug string) (*QuizInfo, error) {
	path := fmt.Sprintf("/sdk/v1/quizzes/%s", slug)
	var result QuizInfo
	err := r.client.request(
		ctx,
		"GET",
		path,
		nil,
		nil,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// SubmitQuiz 
func (r *QuizzesResource) SubmitQuiz(ctx context.Context, slug string, request *QuizSubmitRequest) (*QuizSubmitResponse, error) {
	path := fmt.Sprintf("/sdk/v1/quizzes/%s/submit", slug)
	var result QuizSubmitResponse
	err := r.client.request(
		ctx,
		"POST",
		path,
		nil,
		request,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// BillingResource provides access to billing resources.
type BillingResource struct {
	client *Client
}



// CreateCheckoutSession 
func (r *BillingResource) CreateCheckoutSession(ctx context.Context, request *CheckoutRequest) (*CheckoutResponse, error) {
	var result CheckoutResponse
	err := r.client.request(
		ctx,
		"POST",
		"/sdk/v1/billing/checkout",
		nil,
		request,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// CreateCustomer 
func (r *BillingResource) CreateCustomer(ctx context.Context, request *CustomerRequest) (*CustomerResponse, error) {
	var result CustomerResponse
	err := r.client.request(
		ctx,
		"POST",
		"/sdk/v1/billing/customers",
		nil,
		request,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// GetCustomerPortal 
func (r *BillingResource) GetCustomerPortal(ctx context.Context, request *PortalRequest) (*PortalResponse, error) {
	var result PortalResponse
	err := r.client.request(
		ctx,
		"POST",
		"/sdk/v1/billing/portal",
		nil,
		request,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// CreateSubscription 
func (r *BillingResource) CreateSubscription(ctx context.Context, request *SubscriptionRequest) (*SubscriptionResponse, error) {
	var result SubscriptionResponse
	err := r.client.request(
		ctx,
		"POST",
		"/sdk/v1/billing/subscriptions",
		nil,
		request,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// CancelSubscription 
func (r *BillingResource) CancelSubscription(ctx context.Context, id string) (*Response, error) {
	path := fmt.Sprintf("/sdk/v1/billing/subscriptions/%s/cancel", id)
	var result Response
	err := r.client.request(
		ctx,
		"POST",
		path,
		nil,
		nil,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// RecordUsage 
func (r *BillingResource) RecordUsage(ctx context.Context, request *UsageRequest) (*Response, error) {
	var result Response
	err := r.client.request(
		ctx,
		"POST",
		"/sdk/v1/billing/usage",
		nil,
		request,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// ContentResource provides access to content resources.
type ContentResource struct {
	client *Client
}



// ListContentCategories 
func (r *ContentResource) ListContentCategories(ctx context.Context) (*ListSDKContentCategoriesResponse, error) {
	var result ListSDKContentCategoriesResponse
	err := r.client.request(
		ctx,
		"GET",
		"/sdk/v1/content/categories",
		nil,
		nil,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// ListContentPages 
func (r *ContentResource) ListContentPages(ctx context.Context, page int, pageSize int) (*ListSDKContentPagesResponse, error) {
	query := url.Values{}
	if page != 0 {
		query.Set("page", strconv.Itoa(page))
	}
	if pageSize != 0 {
		query.Set("page_size", strconv.Itoa(pageSize))
	}
	var result ListSDKContentPagesResponse
	err := r.client.request(
		ctx,
		"GET",
		"/sdk/v1/content/pages",
		query,
		nil,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// GetContentPage 
func (r *ContentResource) GetContentPage(ctx context.Context, slug string) (*SDKContentPageInfo, error) {
	path := fmt.Sprintf("/sdk/v1/content/pages/%s", slug)
	var result SDKContentPageInfo
	err := r.client.request(
		ctx,
		"GET",
		path,
		nil,
		nil,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// ListContentPosts 
func (r *ContentResource) ListContentPosts(ctx context.Context, page int, pageSize int, categorySlug string) (*ListSDKContentPostsResponse, error) {
	query := url.Values{}
	if page != 0 {
		query.Set("page", strconv.Itoa(page))
	}
	if pageSize != 0 {
		query.Set("page_size", strconv.Itoa(pageSize))
	}
	if categorySlug != "" {
		query.Set("category", categorySlug)
	}
	var result ListSDKContentPostsResponse
	err := r.client.request(
		ctx,
		"GET",
		"/sdk/v1/content/posts",
		query,
		nil,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// GetContentPost 
func (r *ContentResource) GetContentPost(ctx context.Context, slug string) (*SDKContentPostInfo, error) {
	path := fmt.Sprintf("/sdk/v1/content/posts/%s", slug)
	var result SDKContentPostInfo
	err := r.client.request(
		ctx,
		"GET",
		path,
		nil,
		nil,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// EmailsResource provides access to emails resources.
type EmailsResource struct {
	client *Client
}



// SendEmail 
func (r *EmailsResource) SendEmail(ctx context.Context, request *SendEmailRequest) (*SendEmailResponse, error) {
	var result SendEmailResponse
	err := r.client.request(
		ctx,
		"POST",
		"/sdk/v1/emails/",
		nil,
		request,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// GetEmailStatus 
func (r *EmailsResource) GetEmailStatus(ctx context.Context, messageId string) (*EmailStatusResponse, error) {
	path := fmt.Sprintf("/sdk/v1/emails/%s", messageId)
	var result EmailStatusResponse
	err := r.client.request(
		ctx,
		"GET",
		path,
		nil,
		nil,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// ListEmailEvents 
func (r *EmailsResource) ListEmailEvents(ctx context.Context, messageId string) (*ListEmailEventsResponse, error) {
	path := fmt.Sprintf("/sdk/v1/emails/%s/events", messageId)
	var result ListEmailEventsResponse
	err := r.client.request(
		ctx,
		"GET",
		path,
		nil,
		nil,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// CustomersResource provides access to customers resources.
type CustomersResource struct {
	client *Client
}



// GetCustomerByEmail 
func (r *CustomersResource) GetCustomerByEmail(ctx context.Context, email string) (*SDKCustomerInfo, error) {
	path := fmt.Sprintf("/sdk/v1/customers/%s", email)
	var result SDKCustomerInfo
	err := r.client.request(
		ctx,
		"GET",
		path,
		nil,
		nil,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// ListCustomerInvoices 
func (r *CustomersResource) ListCustomerInvoices(ctx context.Context, email string, limit int) (*ListCustomerInvoicesResponse, error) {
	path := fmt.Sprintf("/sdk/v1/customers/%s/invoices", email)
	query := url.Values{}
	if limit != 0 {
		query.Set("limit", strconv.Itoa(limit))
	}
	var result ListCustomerInvoicesResponse
	err := r.client.request(
		ctx,
		"GET",
		path,
		query,
		nil,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// ListCustomerOrders 
func (r *CustomersResource) ListCustomerOrders(ctx context.Context, email string, limit int) (*ListCustomerOrdersResponse, error) {
	path := fmt.Sprintf("/sdk/v1/customers/%s/orders", email)
	query := url.Values{}
	if limit != 0 {
		query.Set("limit", strconv.Itoa(limit))
	}
	var result ListCustomerOrdersResponse
	err := r.client.request(
		ctx,
		"GET",
		path,
		query,
		nil,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// ListCustomerPayments 
func (r *CustomersResource) ListCustomerPayments(ctx context.Context, email string, limit int) (*ListCustomerPaymentsResponse, error) {
	path := fmt.Sprintf("/sdk/v1/customers/%s/payments", email)
	query := url.Values{}
	if limit != 0 {
		query.Set("limit", strconv.Itoa(limit))
	}
	var result ListCustomerPaymentsResponse
	err := r.client.request(
		ctx,
		"GET",
		path,
		query,
		nil,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// ListCustomerSubscriptions 
func (r *CustomersResource) ListCustomerSubscriptions(ctx context.Context, email string) (*ListCustomerSubscriptionsResponse, error) {
	path := fmt.Sprintf("/sdk/v1/customers/%s/subscriptions", email)
	var result ListCustomerSubscriptionsResponse
	err := r.client.request(
		ctx,
		"GET",
		path,
		nil,
		nil,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// SequencesResource provides access to sequences resources.
type SequencesResource struct {
	client *Client
}



// EnrollInSequence 
func (r *SequencesResource) EnrollInSequence(ctx context.Context, request *EnrollSequenceRequest) (*EnrollSequenceResponse, error) {
	var result EnrollSequenceResponse
	err := r.client.request(
		ctx,
		"POST",
		"/sdk/v1/sequences/enroll",
		nil,
		request,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// GetSequenceEnrollments 
func (r *SequencesResource) GetSequenceEnrollments(ctx context.Context, email string, sequenceSlug string) (*ListSequenceEnrollmentsResponse, error) {
	query := url.Values{}
	query.Set("email", email)
	if sequenceSlug != "" {
		query.Set("sequence_slug", sequenceSlug)
	}
	var result ListSequenceEnrollmentsResponse
	err := r.client.request(
		ctx,
		"GET",
		"/sdk/v1/sequences/enrollments",
		query,
		nil,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// PauseSequenceEnrollment 
func (r *SequencesResource) PauseSequenceEnrollment(ctx context.Context, request *PauseSequenceRequest) (*Response, error) {
	var result Response
	err := r.client.request(
		ctx,
		"POST",
		"/sdk/v1/sequences/pause",
		nil,
		request,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// ResumeSequenceEnrollment 
func (r *SequencesResource) ResumeSequenceEnrollment(ctx context.Context, request *ResumeSequenceRequest) (*Response, error) {
	var result Response
	err := r.client.request(
		ctx,
		"POST",
		"/sdk/v1/sequences/resume",
		nil,
		request,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// UnenrollFromSequence 
func (r *SequencesResource) UnenrollFromSequence(ctx context.Context, request *UnenrollSequenceRequest) (*Response, error) {
	var result Response
	err := r.client.request(
		ctx,
		"POST",
		"/sdk/v1/sequences/unenroll",
		nil,
		request,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// SiteResource provides access to site resources.
type SiteResource struct {
	client *Client
}



// ListAuthors 
func (r *SiteResource) ListAuthors(ctx context.Context) (*ListSDKAuthorsResponse, error) {
	var result ListSDKAuthorsResponse
	err := r.client.request(
		ctx,
		"GET",
		"/sdk/v1/site/authors",
		nil,
		nil,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// GetAuthor 
func (r *SiteResource) GetAuthor(ctx context.Context, id string) (*SDKAuthorInfo, error) {
	path := fmt.Sprintf("/sdk/v1/site/authors/%s", id)
	var result SDKAuthorInfo
	err := r.client.request(
		ctx,
		"GET",
		path,
		nil,
		nil,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// ListNavigationMenus 
func (r *SiteResource) ListNavigationMenus(ctx context.Context, location string) (*ListSDKNavigationMenusResponse, error) {
	query := url.Values{}
	if location != "" {
		query.Set("location", location)
	}
	var result ListSDKNavigationMenusResponse
	err := r.client.request(
		ctx,
		"GET",
		"/sdk/v1/site/menus",
		query,
		nil,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// GetNavigationMenu 
func (r *SiteResource) GetNavigationMenu(ctx context.Context, slug string) (*SDKNavigationMenu, error) {
	path := fmt.Sprintf("/sdk/v1/site/menus/%s", slug)
	var result SDKNavigationMenu
	err := r.client.request(
		ctx,
		"GET",
		path,
		nil,
		nil,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// GetSiteSettings 
func (r *SiteResource) GetSiteSettings(ctx context.Context) (*SDKSiteSettings, error) {
	var result SDKSiteSettings
	err := r.client.request(
		ctx,
		"GET",
		"/sdk/v1/site/settings",
		nil,
		nil,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// OffersResource provides access to offers resources.
type OffersResource struct {
	client *Client
}



// ProcessOffer 
func (r *OffersResource) ProcessOffer(ctx context.Context, request *OfferRequest) (*OfferResponse, error) {
	var result OfferResponse
	err := r.client.request(
		ctx,
		"POST",
		"/sdk/v1/offers",
		nil,
		request,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// LlmResource provides access to llm resources.
type LlmResource struct {
	client *Client
}



// Chat 
func (r *LlmResource) Chat(ctx context.Context, request *LLMChatRequest) (*LLMChatResponse, error) {
	var result LLMChatResponse
	err := r.client.request(
		ctx,
		"POST",
		"/sdk/v1/llm/chat",
		nil,
		request,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// Config 
func (r *LlmResource) Config(ctx context.Context) (*LLMConfigResponse, error) {
	var result LLMConfigResponse
	err := r.client.request(
		ctx,
		"GET",
		"/sdk/v1/llm/config",
		nil,
		nil,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// StatsResource provides access to stats resources.
type StatsResource struct {
	client *Client
}



// GetContactStats 
func (r *StatsResource) GetContactStats(ctx context.Context, startDate string, endDate string, groupBy string) (*GetContactStatsResponse, error) {
	query := url.Values{}
	if startDate != "" {
		query.Set("start_date", startDate)
	}
	if endDate != "" {
		query.Set("end_date", endDate)
	}
	if groupBy != "" {
		query.Set("group_by", groupBy)
	}
	var result GetContactStatsResponse
	err := r.client.request(
		ctx,
		"GET",
		"/sdk/v1/stats/contacts",
		query,
		nil,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// GetEmailStats 
func (r *StatsResource) GetEmailStats(ctx context.Context, startDate string, endDate string, groupBy string) (*GetEmailStatsResponse, error) {
	query := url.Values{}
	if startDate != "" {
		query.Set("start_date", startDate)
	}
	if endDate != "" {
		query.Set("end_date", endDate)
	}
	if groupBy != "" {
		query.Set("group_by", groupBy)
	}
	var result GetEmailStatsResponse
	err := r.client.request(
		ctx,
		"GET",
		"/sdk/v1/stats/emails",
		query,
		nil,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// GetStatsOverview 
func (r *StatsResource) GetStatsOverview(ctx context.Context, startDate string, endDate string) (*StatsOverviewResponse, error) {
	query := url.Values{}
	if startDate != "" {
		query.Set("start_date", startDate)
	}
	if endDate != "" {
		query.Set("end_date", endDate)
	}
	var result StatsOverviewResponse
	err := r.client.request(
		ctx,
		"GET",
		"/sdk/v1/stats/overview",
		query,
		nil,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// GetRevenueStats 
func (r *StatsResource) GetRevenueStats(ctx context.Context, startDate string, endDate string, groupBy string) (*GetRevenueStatsResponse, error) {
	query := url.Values{}
	if startDate != "" {
		query.Set("start_date", startDate)
	}
	if endDate != "" {
		query.Set("end_date", endDate)
	}
	if groupBy != "" {
		query.Set("group_by", groupBy)
	}
	var result GetRevenueStatsResponse
	err := r.client.request(
		ctx,
		"GET",
		"/sdk/v1/stats/revenue",
		query,
		nil,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// TrackingResource provides access to tracking resources.
type TrackingResource struct {
	client *Client
}



// TrackClick 
func (r *TrackingResource) TrackClick(ctx context.Context, request *TrackClickRequest) (*Response, error) {
	var result Response
	err := r.client.request(
		ctx,
		"POST",
		"/sdk/v1/tracking/click",
		nil,
		request,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// TrackConfirm 
func (r *TrackingResource) TrackConfirm(ctx context.Context, request *TrackConfirmRequest) (*TrackConfirmResponse, error) {
	var result TrackConfirmResponse
	err := r.client.request(
		ctx,
		"POST",
		"/sdk/v1/tracking/confirm",
		nil,
		request,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// TrackOpen 
func (r *TrackingResource) TrackOpen(ctx context.Context, request *TrackOpenRequest) (*Response, error) {
	var result Response
	err := r.client.request(
		ctx,
		"POST",
		"/sdk/v1/tracking/open",
		nil,
		request,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// TrackUnsubscribe 
func (r *TrackingResource) TrackUnsubscribe(ctx context.Context, request *TrackUnsubscribeRequest) (*Response, error) {
	var result Response
	err := r.client.request(
		ctx,
		"POST",
		"/sdk/v1/tracking/unsubscribe",
		nil,
		request,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// WebhooksResource provides access to webhooks resources.
type WebhooksResource struct {
	client *Client
}



// RegisterWebhook 
func (r *WebhooksResource) RegisterWebhook(ctx context.Context, request *RegisterWebhookRequest) (*RegisterWebhookResponse, error) {
	var result RegisterWebhookResponse
	err := r.client.request(
		ctx,
		"POST",
		"/sdk/v1/webhooks/",
		nil,
		request,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// ListWebhooks 
func (r *WebhooksResource) ListWebhooks(ctx context.Context) (*ListWebhooksResponse, error) {
	var result ListWebhooksResponse
	err := r.client.request(
		ctx,
		"GET",
		"/sdk/v1/webhooks/",
		nil,
		nil,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// GetWebhook 
func (r *WebhooksResource) GetWebhook(ctx context.Context, id string) (*WebhookInfo, error) {
	path := fmt.Sprintf("/sdk/v1/webhooks/%s", id)
	var result WebhookInfo
	err := r.client.request(
		ctx,
		"GET",
		path,
		nil,
		nil,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// UpdateWebhook 
func (r *WebhooksResource) UpdateWebhook(ctx context.Context, id string, request *UpdateWebhookRequest) (*WebhookInfo, error) {
	path := fmt.Sprintf("/sdk/v1/webhooks/%s", id)
	var result WebhookInfo
	err := r.client.request(
		ctx,
		"PUT",
		path,
		nil,
		request,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// DeleteWebhook 
func (r *WebhooksResource) DeleteWebhook(ctx context.Context, id string) (*Response, error) {
	path := fmt.Sprintf("/sdk/v1/webhooks/%s", id)
	var result Response
	err := r.client.request(
		ctx,
		"DELETE",
		path,
		nil,
		nil,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// ListWebhookLogs 
func (r *WebhooksResource) ListWebhookLogs(ctx context.Context, id string, limit int) (*ListWebhookLogsResponse, error) {
	path := fmt.Sprintf("/sdk/v1/webhooks/%s/logs", id)
	query := url.Values{}
	if limit != 0 {
		query.Set("limit", strconv.Itoa(limit))
	}
	var result ListWebhookLogsResponse
	err := r.client.request(
		ctx,
		"GET",
		path,
		query,
		nil,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// TestWebhook 
func (r *WebhooksResource) TestWebhook(ctx context.Context, id string) (*TestWebhookResponse, error) {
	path := fmt.Sprintf("/sdk/v1/webhooks/%s/test", id)
	var result TestWebhookResponse
	err := r.client.request(
		ctx,
		"POST",
		path,
		nil,
		nil,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// ContactsResource provides access to contacts resources.
type ContactsResource struct {
	client *Client
}



// CreateContact 
func (r *ContactsResource) CreateContact(ctx context.Context, request *ContactRequest) (*ContactResponse, error) {
	var result ContactResponse
	err := r.client.request(
		ctx,
		"POST",
		"/sdk/v1/contacts",
		nil,
		request,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// GetContact 
func (r *ContactsResource) GetContact(ctx context.Context, id string) (*SDKContactInfo, error) {
	path := fmt.Sprintf("/sdk/v1/contacts/%s", id)
	var result SDKContactInfo
	err := r.client.request(
		ctx,
		"GET",
		path,
		nil,
		nil,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// UpdateContact 
func (r *ContactsResource) UpdateContact(ctx context.Context, id string, request *UpdateContactRequest) (*SDKContactInfo, error) {
	path := fmt.Sprintf("/sdk/v1/contacts/%s", id)
	var result SDKContactInfo
	err := r.client.request(
		ctx,
		"PUT",
		path,
		nil,
		request,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// ListContactActivity 
func (r *ContactsResource) ListContactActivity(ctx context.Context, id string, limit int) (*ListContactActivityResponse, error) {
	path := fmt.Sprintf("/sdk/v1/contacts/%s/activity", id)
	query := url.Values{}
	if limit != 0 {
		query.Set("limit", strconv.Itoa(limit))
	}
	var result ListContactActivityResponse
	err := r.client.request(
		ctx,
		"GET",
		path,
		query,
		nil,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// AddContactTags 
func (r *ContactsResource) AddContactTags(ctx context.Context, id string, request *AddContactTagsRequest) (*Response, error) {
	path := fmt.Sprintf("/sdk/v1/contacts/%s/tags", id)
	var result Response
	err := r.client.request(
		ctx,
		"POST",
		path,
		nil,
		request,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// RemoveContactTags 
func (r *ContactsResource) RemoveContactTags(ctx context.Context, id string, request *RemoveContactTagsRequest) (*Response, error) {
	path := fmt.Sprintf("/sdk/v1/contacts/%s/tags", id)
	var result Response
	err := r.client.request(
		ctx,
		"DELETE",
		path,
		nil,
		request,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// GlobalUnsubscribe 
func (r *ContactsResource) GlobalUnsubscribe(ctx context.Context, request *GlobalUnsubscribeRequest) (*Response, error) {
	var result Response
	err := r.client.request(
		ctx,
		"POST",
		"/sdk/v1/contacts/unsubscribe",
		nil,
		request,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// ListsResource provides access to lists resources.
type ListsResource struct {
	client *Client
}



// SubscribeToList 
func (r *ListsResource) SubscribeToList(ctx context.Context, slug string, request *SubscribeRequest) (*Response, error) {
	path := fmt.Sprintf("/sdk/v1/lists/%s/subscribe", slug)
	var result Response
	err := r.client.request(
		ctx,
		"POST",
		path,
		nil,
		request,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// UnsubscribeFromList 
func (r *ListsResource) UnsubscribeFromList(ctx context.Context, slug string, request *SubscribeRequest) (*Response, error) {
	path := fmt.Sprintf("/sdk/v1/lists/%s/unsubscribe", slug)
	var result Response
	err := r.client.request(
		ctx,
		"POST",
		path,
		nil,
		request,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// WorkshopsResource provides access to workshops resources.
type WorkshopsResource struct {
	client *Client
}



// GetWorkshop 
func (r *WorkshopsResource) GetWorkshop(ctx context.Context, slug string) (*WorkshopEventInfo, error) {
	path := fmt.Sprintf("/sdk/v1/workshops/%s", slug)
	var result WorkshopEventInfo
	err := r.client.request(
		ctx,
		"GET",
		path,
		nil,
		nil,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}



// GetWorkshopByProduct 
func (r *WorkshopsResource) GetWorkshopByProduct(ctx context.Context, productSlug string) (*WorkshopEventInfo, error) {
	path := fmt.Sprintf("/sdk/v1/workshops/product/%s", productSlug)
	var result WorkshopEventInfo
	err := r.client.request(
		ctx,
		"GET",
		path,
		nil,
		nil,
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
}




// Ensure packages are used
var _ = strings.TrimSpace
var _ = strconv.Itoa
