// Code generated by goctl-sdk. DO NOT EDIT.

package levee


// AddContactTagsRequest represents the AddContactTagsRequest type.
type AddContactTagsRequest struct {
	Tags []string `json:"tags"`
}


// ProductFeature represents the ProductFeature type.
type ProductFeature struct {
	Name string `json:"name"`
	Description string `json:"description,omitempty"`
	Included bool `json:"included"`
}


// PriceTierInfo represents the PriceTierInfo type.
type PriceTierInfo struct {
	ID string `json:"id"`
	PriceID string `json:"price_id"`
	TierType string `json:"tier_type"`
	UpTo int `json:"up_to,omitempty"`
	UnitAmountCents int64 `json:"unit_amount_cents"`
	FlatAmountCents int64 `json:"flat_amount_cents"`
	CreatedAt string `json:"created_at"`
}


// PriceCurrencyInfo represents the PriceCurrencyInfo type.
type PriceCurrencyInfo struct {
	ID string `json:"id"`
	PriceID string `json:"price_id"`
	Currency string `json:"currency"`
	UnitAmountCents int64 `json:"unit_amount_cents"`
	CompareAtCents int64 `json:"compare_at_cents,omitempty"`
	CreatedAt string `json:"created_at"`
}


// BillingPriceInfo represents the BillingPriceInfo type.
type BillingPriceInfo struct {
	ID string `json:"id"`
	OrgID string `json:"org_id"`
	ProductID string `json:"product_id"`
	ProductName string `json:"product_name,omitempty"`
	StripePriceID string `json:"stripe_price_id,omitempty"`
	Provider string `json:"provider,omitempty"`
	ProviderPriceID string `json:"provider_price_id,omitempty"`
	Nickname string `json:"nickname,omitempty"`
	DisplayName string `json:"display_name,omitempty"`
	UnitAmountCents int64 `json:"unit_amount_cents"`
	CompareAtCents int64 `json:"compare_at_cents,omitempty"`
	Currency string `json:"currency"`
	RecurringInterval string `json:"recurring_interval,omitempty"`
	RecurringIntervalCount int `json:"recurring_interval_count,omitempty"`
	UsageType string `json:"usage_type"`
	Active bool `json:"active"`
	PriceType string `json:"price_type"`
	BillingModel string `json:"billing_model"`
	MinimumQuantity int `json:"minimum_quantity,omitempty"`
	MaximumQuantity int `json:"maximum_quantity,omitempty"`
	TrialPeriodDays int `json:"trial_period_days,omitempty"`
	IncludedUnits int `json:"included_units,omitempty"`
	OverageUnitAmountCents int64 `json:"overage_unit_amount_cents,omitempty"`
	FeatureLimits map[string]interface{} `json:"feature_limits,omitempty"`
	DisplayOrder int `json:"display_order"`
	Highlighted bool `json:"highlighted"`
	Tiers []PriceTierInfo `json:"tiers,omitempty"`
	Currencies []PriceCurrencyInfo `json:"currencies,omitempty"`
	CreatedAt string `json:"created_at"`
}


// BillingProductInfo represents the BillingProductInfo type.
type BillingProductInfo struct {
	ID string `json:"id"`
	OrgID string `json:"org_id"`
	Slug string `json:"slug,omitempty"`
	StripeProductID string `json:"stripe_product_id,omitempty"`
	Provider string `json:"provider,omitempty"`
	ProviderProductID string `json:"provider_product_id,omitempty"`
	Name string `json:"name"`
	Description string `json:"description,omitempty"`
	Tagline string `json:"tagline,omitempty"`
	Type string `json:"type"`
	Category string `json:"category"`
	DeliveryMethod string `json:"delivery_method,omitempty"`
	Active bool `json:"active"`
	Features []ProductFeature `json:"features,omitempty"`
	WhatsIncluded []string `json:"whats_included,omitempty"`
	WhoItsFor []string `json:"who_its_for,omitempty"`
	TaxCode string `json:"tax_code,omitempty"`
	UnitLabel string `json:"unit_label,omitempty"`
	Shippable bool `json:"shippable"`
	Images []string `json:"images,omitempty"`
	InventoryType string `json:"inventory_type,omitempty"`
	InventoryCount int `json:"inventory_count,omitempty"`
	LowStockThreshold int `json:"low_stock_threshold,omitempty"`
	DisplayOrder int `json:"display_order"`
	Highlighted bool `json:"highlighted"`
	CtaText string `json:"cta_text,omitempty"`
	Prices []BillingPriceInfo `json:"prices,omitempty"`
	EmailSequenceID int64 `json:"email_sequence_id,omitempty"`
	CreatedAt string `json:"created_at"`
}


// CheckoutItem represents the CheckoutItem type.
type CheckoutItem struct {
	PriceID string `json:"price_id"`
	Quantity int `json:"quantity"`
}


// CheckoutRequest represents the CheckoutRequest type.
type CheckoutRequest struct {
	CustomerEmail string `json:"customer_email"`
	LineItems []CheckoutItem `json:"line_items"`
	Mode string `json:"mode"`
	SuccessUrl string `json:"success_url,omitempty"`
	CancelUrl string `json:"cancel_url,omitempty"`
	Embedded bool `json:"embedded,omitempty"`
	ReturnUrl string `json:"return_url,omitempty"`
}


// CheckoutResponse represents the CheckoutResponse type.
type CheckoutResponse struct {
	SessionID string `json:"session_id"`
	CheckoutUrl string `json:"checkout_url,omitempty"`
	ClientSecret string `json:"client_secret,omitempty"`
}


// ContactRequest represents the ContactRequest type.
type ContactRequest struct {
	Email string `json:"email"`
	Name string `json:"name,omitempty"`
	Phone string `json:"phone,omitempty"`
	Company string `json:"company,omitempty"`
	Employees string `json:"employees,omitempty"`
	Message string `json:"message,omitempty"`
	Source string `json:"source,omitempty"`
	Tags []string `json:"tags,omitempty"`
	FunnelSlug string `json:"funnel_slug,omitempty"`
	ListSlug string `json:"list_slug,omitempty"`
	Score bool `json:"score,omitempty"`
	UtmSource string `json:"utm_source,omitempty"`
	UtmMedium string `json:"utm_medium,omitempty"`
	UtmCampaign string `json:"utm_campaign,omitempty"`
	Meta map[string]string `json:"meta,omitempty"`
}


// ContactResponse represents the ContactResponse type.
type ContactResponse struct {
	ID string `json:"id"`
	Email string `json:"email"`
	Name string `json:"name"`
	Score int `json:"score,omitempty"`
	Qualified bool `json:"qualified,omitempty"`
	Reasoning string `json:"reasoning,omitempty"`
	NextSteps string `json:"next_steps,omitempty"`
}


// CustomerRequest represents the CustomerRequest type.
type CustomerRequest struct {
	Email string `json:"email"`
	Name string `json:"name,omitempty"`
	Phone string `json:"phone,omitempty"`
	Meta map[string]string `json:"meta,omitempty"`
}


// CustomerResponse represents the CustomerResponse type.
type CustomerResponse struct {
	ID string `json:"id"`
	StripeCustomerID string `json:"stripe_customer_id"`
	Email string `json:"email"`
	Name string `json:"name"`
}


// EmailStatusResponse represents the EmailStatusResponse type.
type EmailStatusResponse struct {
	MessageID string `json:"message_id"`
	To string `json:"to"`
	Subject string `json:"subject"`
	Status string `json:"status"`
	SentAt string `json:"sent_at,omitempty"`
	DeliveredAt string `json:"delivered_at,omitempty"`
	OpenedAt string `json:"opened_at,omitempty"`
	ClickedAt string `json:"clicked_at,omitempty"`
	BouncedAt string `json:"bounced_at,omitempty"`
	BounceType string `json:"bounce_type,omitempty"`
	Opens int `json:"opens"`
	Clicks int `json:"clicks"`
}


// EnrollSequenceRequest represents the EnrollSequenceRequest type.
type EnrollSequenceRequest struct {
	SequenceSlug string `json:"sequence_slug"`
	Email string `json:"email"`
	Variables map[string]string `json:"variables,omitempty"`
	StartAtStep int `json:"start_at_step,omitempty"`
	ScheduledFor string `json:"scheduled_for,omitempty"`
}


// EnrollSequenceResponse represents the EnrollSequenceResponse type.
type EnrollSequenceResponse struct {
	Success bool `json:"success"`
	EnrollmentID string `json:"enrollment_id"`
	Status string `json:"status"`
	Message string `json:"message,omitempty"`
}


// EventRequest represents the EventRequest type.
type EventRequest struct {
	Event string `json:"event"`
	Email string `json:"email,omitempty"`
	VisitorID string `json:"visitor_id,omitempty"`
	SessionID string `json:"session_id,omitempty"`
	Page string `json:"page,omitempty"`
	Referrer string `json:"referrer,omitempty"`
	FunnelSlug string `json:"funnel_slug,omitempty"`
	FunnelStep string `json:"funnel_step,omitempty"`
	ScrollDepth int `json:"scroll_depth,omitempty"`
	Properties map[string]interface{} `json:"properties,omitempty"`
	UtmSource string `json:"utm_source,omitempty"`
	UtmMedium string `json:"utm_medium,omitempty"`
	UtmCampaign string `json:"utm_campaign,omitempty"`
}


// FunnelStepInfo represents the FunnelStepInfo type.
type FunnelStepInfo struct {
	ID int64 `json:"id"`
	FunnelID int64 `json:"funnel_id"`
	FunnelSlug string `json:"funnel_slug,omitempty"`
	Slug string `json:"slug"`
	StepType string `json:"step_type"`
	Position int `json:"position"`
	Title string `json:"title"`
	Headline string `json:"headline,omitempty"`
	Subheadline string `json:"subheadline,omitempty"`
	Content map[string]interface{} `json:"content,omitempty"`
	ProductID string `json:"product_id,omitempty"`
	Product BillingProductInfo `json:"product,omitempty"`
	OrderBumpProductID string `json:"order_bump_product_id,omitempty"`
	OrderBumpProduct BillingProductInfo `json:"order_bump_product,omitempty"`
	OrderBumpHeadline string `json:"order_bump_headline,omitempty"`
	OrderBumpDescription string `json:"order_bump_description,omitempty"`
	NextStepID int64 `json:"next_step_id,omitempty"`
	DeclineStepID int64 `json:"decline_step_id,omitempty"`
	SuccessRedirect string `json:"success_redirect,omitempty"`
	EmailSequenceID int64 `json:"email_sequence_id,omitempty"`
	TriggerEvent string `json:"trigger_event,omitempty"`
	IsActive bool `json:"is_active"`
	CreatedAt string `json:"created_at"`
}


// ContactStatsPoint represents the ContactStatsPoint type.
type ContactStatsPoint struct {
	Date string `json:"date"`
	NewContacts int `json:"new_contacts"`
	Unsubscribed int `json:"unsubscribed"`
	Bounced int `json:"bounced"`
	NetGrowth int `json:"net_growth"`
}


// GetContactStatsResponse represents the GetContactStatsResponse type.
type GetContactStatsResponse struct {
	Stats []ContactStatsPoint `json:"stats"`
	TotalActive int `json:"total_active"`
	TotalUnsubscribed int `json:"total_unsubscribed"`
	TotalBounced int `json:"total_bounced"`
	NetGrowth int `json:"net_growth"`
}


// EmailStatsPoint represents the EmailStatsPoint type.
type EmailStatsPoint struct {
	Date string `json:"date"`
	Sent int `json:"sent"`
	Delivered int `json:"delivered"`
	Opened int `json:"opened"`
	Clicked int `json:"clicked"`
	Bounced int `json:"bounced"`
	OpenRate float64 `json:"open_rate"`
	ClickRate float64 `json:"click_rate"`
}


// GetEmailStatsResponse represents the GetEmailStatsResponse type.
type GetEmailStatsResponse struct {
	Stats []EmailStatsPoint `json:"stats"`
	TotalSent int `json:"total_sent"`
	TotalDelivered int `json:"total_delivered"`
	TotalOpened int `json:"total_opened"`
	TotalClicked int `json:"total_clicked"`
	TotalBounced int `json:"total_bounced"`
	AvgOpenRate float64 `json:"avg_open_rate"`
	AvgClickRate float64 `json:"avg_click_rate"`
}


// RevenueStatsPoint represents the RevenueStatsPoint type.
type RevenueStatsPoint struct {
	Date string `json:"date"`
	Revenue int64 `json:"revenue"`
	OrderCount int `json:"order_count"`
	NewSubscriptions int `json:"new_subscriptions"`
	Churned int `json:"churned"`
}


// GetRevenueStatsResponse represents the GetRevenueStatsResponse type.
type GetRevenueStatsResponse struct {
	Stats []RevenueStatsPoint `json:"stats"`
	TotalRevenue int64 `json:"total_revenue"`
	TotalOrders int `json:"total_orders"`
	TotalSubscriptions int `json:"total_subscriptions"`
	TotalChurned int `json:"total_churned"`
	Mrr int64 `json:"mrr"`
}


// GlobalUnsubscribeRequest represents the GlobalUnsubscribeRequest type.
type GlobalUnsubscribeRequest struct {
	Email string `json:"email"`
	Reason string `json:"reason,omitempty"`
}


// LLMMessage represents the LLMMessage type.
type LLMMessage struct {
	Role string `json:"role"`
	Content string `json:"content"`
}


// LLMChatRequest represents the LLMChatRequest type.
type LLMChatRequest struct {
	Messages []LLMMessage `json:"messages"`
	SystemPrompt string `json:"system_prompt,omitempty"`
	Model string `json:"model,omitempty"`
	MaxTokens int `json:"max_tokens,omitempty"`
	Temperature float64 `json:"temperature,omitempty"`
}


// LLMChatResponse represents the LLMChatResponse type.
type LLMChatResponse struct {
	Content string `json:"content"`
	Model string `json:"model"`
	InputTokens int64 `json:"input_tokens"`
	OutputTokens int64 `json:"output_tokens"`
	CostUsd float64 `json:"cost_usd"`
	LatencyMs int64 `json:"latency_ms"`
	StopReason string `json:"stop_reason"`
}


// LLMConfigResponse represents the LLMConfigResponse type.
type LLMConfigResponse struct {
	Available bool `json:"available"`
	DefaultProvider string `json:"default_provider"`
	ConfiguredProviders []string `json:"configured_providers"`
	GrpcPort int `json:"grpc_port"`
}


// ContactActivityInfo represents the ContactActivityInfo type.
type ContactActivityInfo struct {
	Event string `json:"event"`
	Timestamp string `json:"timestamp"`
	Details string `json:"details,omitempty"`
}


// ListContactActivityResponse represents the ListContactActivityResponse type.
type ListContactActivityResponse struct {
	Activities []ContactActivityInfo `json:"activities"`
}


// SDKInvoiceInfo represents the SDKInvoiceInfo type.
type SDKInvoiceInfo struct {
	ID string `json:"id"`
	StripeInvoiceID string `json:"stripe_invoice_id,omitempty"`
	Number string `json:"number"`
	Status string `json:"status"`
	AmountDue int64 `json:"amount_due"`
	AmountPaid int64 `json:"amount_paid"`
	Currency string `json:"currency"`
	Description string `json:"description,omitempty"`
	InvoicePdfUrl string `json:"invoice_pdf_url,omitempty"`
	HostedUrl string `json:"hosted_url,omitempty"`
	DueDate string `json:"due_date,omitempty"`
	PaidAt string `json:"paid_at,omitempty"`
	CreatedAt string `json:"created_at"`
}


// ListCustomerInvoicesResponse represents the ListCustomerInvoicesResponse type.
type ListCustomerInvoicesResponse struct {
	Invoices []SDKInvoiceInfo `json:"invoices"`
	Total int `json:"total"`
}


// SDKOrderItem represents the SDKOrderItem type.
type SDKOrderItem struct {
	ProductName string `json:"product_name"`
	Quantity int `json:"quantity"`
	UnitPrice int64 `json:"unit_price"`
	TotalPrice int64 `json:"total_price"`
}


// SDKOrderInfo represents the SDKOrderInfo type.
type SDKOrderInfo struct {
	ID string `json:"id"`
	OrderNumber string `json:"order_number"`
	Status string `json:"status"`
	TotalCents int64 `json:"total_cents"`
	Currency string `json:"currency"`
	Items []SDKOrderItem `json:"items"`
	PaymentMethod string `json:"payment_method,omitempty"`
	PaidAt string `json:"paid_at,omitempty"`
	FulfilledAt string `json:"fulfilled_at,omitempty"`
	CreatedAt string `json:"created_at"`
}


// ListCustomerOrdersResponse represents the ListCustomerOrdersResponse type.
type ListCustomerOrdersResponse struct {
	Orders []SDKOrderInfo `json:"orders"`
	Total int `json:"total"`
}


// SDKPaymentInfo represents the SDKPaymentInfo type.
type SDKPaymentInfo struct {
	ID string `json:"id"`
	StripePaymentID string `json:"stripe_payment_id,omitempty"`
	AmountCents int64 `json:"amount_cents"`
	Currency string `json:"currency"`
	Status string `json:"status"`
	Description string `json:"description,omitempty"`
	PaymentMethod string `json:"payment_method,omitempty"`
	ReceiptUrl string `json:"receipt_url,omitempty"`
	RefundedAt string `json:"refunded_at,omitempty"`
	CreatedAt string `json:"created_at"`
}


// ListCustomerPaymentsResponse represents the ListCustomerPaymentsResponse type.
type ListCustomerPaymentsResponse struct {
	Payments []SDKPaymentInfo `json:"payments"`
	Total int `json:"total"`
}


// SDKSubscriptionInfo represents the SDKSubscriptionInfo type.
type SDKSubscriptionInfo struct {
	ID string `json:"id"`
	StripeSubscriptionID string `json:"stripe_subscription_id,omitempty"`
	ProductName string `json:"product_name"`
	PriceName string `json:"price_name,omitempty"`
	Status string `json:"status"`
	AmountCents int64 `json:"amount_cents"`
	Currency string `json:"currency"`
	Interval string `json:"interval"`
	CurrentPeriodStart string `json:"current_period_start"`
	CurrentPeriodEnd string `json:"current_period_end"`
	CancelAtPeriodEnd bool `json:"cancel_at_period_end"`
	TrialEnd string `json:"trial_end,omitempty"`
	CreatedAt string `json:"created_at"`
}


// ListCustomerSubscriptionsResponse represents the ListCustomerSubscriptionsResponse type.
type ListCustomerSubscriptionsResponse struct {
	Subscriptions []SDKSubscriptionInfo `json:"subscriptions"`
}


// EmailEventInfo represents the EmailEventInfo type.
type EmailEventInfo struct {
	Event string `json:"event"`
	Timestamp string `json:"timestamp"`
	Data string `json:"data,omitempty"`
}


// ListEmailEventsResponse represents the ListEmailEventsResponse type.
type ListEmailEventsResponse struct {
	Events []EmailEventInfo `json:"events"`
}


// SDKAuthorInfo represents the SDKAuthorInfo type.
type SDKAuthorInfo struct {
	ID string `json:"id"`
	DisplayName string `json:"display_name"`
	Bio string `json:"bio,omitempty"`
	AvatarUrl string `json:"avatar_url,omitempty"`
	WebsiteUrl string `json:"website_url,omitempty"`
	TwitterHandle string `json:"twitter_handle,omitempty"`
	LinkedinUrl string `json:"linkedin_url,omitempty"`
	GithubHandle string `json:"github_handle,omitempty"`
}


// ListSDKAuthorsResponse represents the ListSDKAuthorsResponse type.
type ListSDKAuthorsResponse struct {
	Authors []SDKAuthorInfo `json:"authors"`
}


// SDKContentCategoryInfo represents the SDKContentCategoryInfo type.
type SDKContentCategoryInfo struct {
	ID string `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
	Description string `json:"description,omitempty"`
}


// ListSDKContentCategoriesResponse represents the ListSDKContentCategoriesResponse type.
type ListSDKContentCategoriesResponse struct {
	Categories []SDKContentCategoryInfo `json:"categories"`
}


// SDKContentPageInfo represents the SDKContentPageInfo type.
type SDKContentPageInfo struct {
	ID string `json:"id"`
	Title string `json:"title"`
	Slug string `json:"slug"`
	Content string `json:"content"`
	Status string `json:"status"`
	MetaTitle string `json:"meta_title,omitempty"`
	MetaDescription string `json:"meta_description,omitempty"`
	FeaturedImage string `json:"featured_image,omitempty"`
	TemplateName string `json:"template_name,omitempty"`
	TemplateSlug string `json:"template_slug,omitempty"`
	CreatedAt string `json:"created_at"`
	PublishedAt string `json:"published_at,omitempty"`
}


// ListSDKContentPagesResponse represents the ListSDKContentPagesResponse type.
type ListSDKContentPagesResponse struct {
	Pages []SDKContentPageInfo `json:"pages"`
	Total int `json:"total"`
}


// SDKContentPostInfo represents the SDKContentPostInfo type.
type SDKContentPostInfo struct {
	ID string `json:"id"`
	Title string `json:"title"`
	Slug string `json:"slug"`
	Content string `json:"content"`
	Excerpt string `json:"excerpt,omitempty"`
	Status string `json:"status"`
	MetaTitle string `json:"meta_title,omitempty"`
	MetaDescription string `json:"meta_description,omitempty"`
	FeaturedImage string `json:"featured_image,omitempty"`
	CategoryName string `json:"category_name,omitempty"`
	CategorySlug string `json:"category_slug,omitempty"`
	AuthorID string `json:"author_id,omitempty"`
	CreatedAt string `json:"created_at"`
	PublishedAt string `json:"published_at,omitempty"`
}


// ListSDKContentPostsResponse represents the ListSDKContentPostsResponse type.
type ListSDKContentPostsResponse struct {
	Posts []SDKContentPostInfo `json:"posts"`
	Total int `json:"total"`
}


// SDKNavigationItem represents the SDKNavigationItem type.
type SDKNavigationItem struct {
	ID string `json:"id"`
	Label string `json:"label"`
	Url string `json:"url,omitempty"`
	Target string `json:"target,omitempty"`
	Icon string `json:"icon,omitempty"`
	IsActive bool `json:"is_active"`
	Children []SDKNavigationItem `json:"children,omitempty"`
}


// SDKNavigationMenu represents the SDKNavigationMenu type.
type SDKNavigationMenu struct {
	ID string `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
	Location string `json:"location"`
	Items []SDKNavigationItem `json:"items"`
}


// ListSDKNavigationMenusResponse represents the ListSDKNavigationMenusResponse type.
type ListSDKNavigationMenusResponse struct {
	Menus []SDKNavigationMenu `json:"menus"`
}


// SequenceEnrollmentInfo represents the SequenceEnrollmentInfo type.
type SequenceEnrollmentInfo struct {
	EnrollmentID string `json:"enrollment_id"`
	SequenceSlug string `json:"sequence_slug"`
	SequenceName string `json:"sequence_name"`
	Status string `json:"status"`
	CurrentStep int `json:"current_step"`
	TotalSteps int `json:"total_steps"`
	EnrolledAt string `json:"enrolled_at"`
	NextEmailAt string `json:"next_email_at,omitempty"`
	CompletedAt string `json:"completed_at,omitempty"`
	EmailsSent int `json:"emails_sent"`
	EmailsOpened int `json:"emails_opened"`
	EmailsClicked int `json:"emails_clicked"`
}


// ListSequenceEnrollmentsResponse represents the ListSequenceEnrollmentsResponse type.
type ListSequenceEnrollmentsResponse struct {
	Enrollments []SequenceEnrollmentInfo `json:"enrollments"`
}


// WebhookLogInfo represents the WebhookLogInfo type.
type WebhookLogInfo struct {
	ID string `json:"id"`
	Event string `json:"event"`
	Payload string `json:"payload"`
	StatusCode int `json:"status_code"`
	Response string `json:"response,omitempty"`
	Error string `json:"error,omitempty"`
	Duration int `json:"duration_ms"`
	DeliveredAt string `json:"delivered_at"`
}


// ListWebhookLogsResponse represents the ListWebhookLogsResponse type.
type ListWebhookLogsResponse struct {
	Logs []WebhookLogInfo `json:"logs"`
}


// WebhookInfo represents the WebhookInfo type.
type WebhookInfo struct {
	ID string `json:"id"`
	Url string `json:"url"`
	Events []string `json:"events"`
	Active bool `json:"active"`
	CreatedAt string `json:"created_at"`
	DeliveriesTotal int `json:"deliveries_total"`
	DeliveriesSuccess int `json:"deliveries_success"`
	DeliveriesFailed int `json:"deliveries_failed"`
	LastDeliveryAt string `json:"last_delivery_at,omitempty"`
	LastStatus int `json:"last_status,omitempty"`
}


// ListWebhooksResponse represents the ListWebhooksResponse type.
type ListWebhooksResponse struct {
	Webhooks []WebhookInfo `json:"webhooks"`
}


// OfferRequest represents the OfferRequest type.
type OfferRequest struct {
	SessionID string `json:"session_id"`
	StepSlug string `json:"step_slug"`
	Accept bool `json:"accept"`
}


// OfferResponse represents the OfferResponse type.
type OfferResponse struct {
	Success bool `json:"success"`
	NextUrl string `json:"next_url,omitempty"`
	OrderItemID int64 `json:"order_item_id,omitempty"`
	Message string `json:"message,omitempty"`
}


// OrderRequest represents the OrderRequest type.
type OrderRequest struct {
	Email string `json:"email"`
	Name string `json:"name,omitempty"`
	Company string `json:"company,omitempty"`
	ProductSlug string `json:"product_slug,omitempty"`
	FunnelStepSlug string `json:"funnel_step_slug,omitempty"`
	WorkshopID int64 `json:"workshop_id,omitempty"`
	IncludeBump bool `json:"include_bump,omitempty"`
	AmountCents int64 `json:"amount_cents,omitempty"`
	Currency string `json:"currency,omitempty"`
	SuccessUrl string `json:"success_url,omitempty"`
	CancelUrl string `json:"cancel_url,omitempty"`
	Meta map[string]string `json:"meta,omitempty"`
}


// OrderResponse represents the OrderResponse type.
type OrderResponse struct {
	Success bool `json:"success"`
	OrderID string `json:"order_id,omitempty"`
	OrderNumber string `json:"order_number,omitempty"`
	CheckoutUrl string `json:"checkout_url,omitempty"`
	SessionID string `json:"session_id,omitempty"`
	Message string `json:"message,omitempty"`
}


// PauseSequenceRequest represents the PauseSequenceRequest type.
type PauseSequenceRequest struct {
	Email string `json:"email"`
	SequenceSlug string `json:"sequence_slug"`
}


// PortalRequest represents the PortalRequest type.
type PortalRequest struct {
	CustomerID string `json:"customer_id"`
	ReturnUrl string `json:"return_url"`
}


// PortalResponse represents the PortalResponse type.
type PortalResponse struct {
	PortalUrl string `json:"portal_url"`
}


// QuizOption represents the QuizOption type.
type QuizOption struct {
	ID string `json:"id"`
	Label string `json:"label"`
	Value string `json:"value"`
	Segments []string `json:"segments,omitempty"`
}


// QuizQuestion represents the QuizQuestion type.
type QuizQuestion struct {
	ID string `json:"id"`
	Question string `json:"question"`
	Type string `json:"type"`
	Options []QuizOption `json:"options,omitempty"`
	Required bool `json:"required"`
}


// QuizInfo represents the QuizInfo type.
type QuizInfo struct {
	Slug string `json:"slug"`
	Title string `json:"title"`
	Description string `json:"description,omitempty"`
	Questions []QuizQuestion `json:"questions"`
}


// QuizSubmitRequest represents the QuizSubmitRequest type.
type QuizSubmitRequest struct {
	QuizSlug string `json:"quiz_slug"`
	Answers map[string]string `json:"answers"`
	Name string `json:"name,omitempty"`
	Email string `json:"email,omitempty"`
}


// QuizSubmitResponse represents the QuizSubmitResponse type.
type QuizSubmitResponse struct {
	Success bool `json:"success"`
	Segments []string `json:"segments"`
	RedirectUrl string `json:"redirect_url,omitempty"`
	LeadID string `json:"lead_id,omitempty"`
}


// RegisterWebhookRequest represents the RegisterWebhookRequest type.
type RegisterWebhookRequest struct {
	Url string `json:"url"`
	Events []string `json:"events"`
	Secret string `json:"secret,omitempty"`
	Active bool `json:"active,omitempty"`
}


// RegisterWebhookResponse represents the RegisterWebhookResponse type.
type RegisterWebhookResponse struct {
	Success bool `json:"success"`
	WebhookID string `json:"webhook_id"`
	Secret string `json:"secret"`
	Message string `json:"message,omitempty"`
}


// RemoveContactTagsRequest represents the RemoveContactTagsRequest type.
type RemoveContactTagsRequest struct {
	Tags []string `json:"tags"`
}


// Response represents the Response type.
type Response struct {
	Success bool `json:"success"`
	Message string `json:"message,omitempty"`
}


// ResumeSequenceRequest represents the ResumeSequenceRequest type.
type ResumeSequenceRequest struct {
	Email string `json:"email"`
	SequenceSlug string `json:"sequence_slug"`
}


// SDKAuthCustomerInfo represents the SDKAuthCustomerInfo type.
type SDKAuthCustomerInfo struct {
	ID string `json:"id"`
	Email string `json:"email"`
	Name string `json:"name,omitempty"`
	EmailVerified bool `json:"email_verified"`
	CreatedAt string `json:"created_at"`
}


// SDKAuthResponse represents the SDKAuthResponse type.
type SDKAuthResponse struct {
	Token string `json:"token"`
	RefreshToken string `json:"refresh_token"`
	ExpiresAt string `json:"expires_at"`
	Customer SDKAuthCustomerInfo `json:"customer"`
	CheckoutUrl string `json:"checkout_url,omitempty"`
}


// SDKChangePasswordRequest represents the SDKChangePasswordRequest type.
type SDKChangePasswordRequest struct {
	Email string `json:"email"`
	CurrentPassword string `json:"current_password"`
	NewPassword string `json:"new_password"`
}


// SDKContactInfo represents the SDKContactInfo type.
type SDKContactInfo struct {
	ID string `json:"id"`
	Email string `json:"email"`
	Name string `json:"name"`
	Phone string `json:"phone,omitempty"`
	Company string `json:"company,omitempty"`
	Status string `json:"status"`
	EmailVerified bool `json:"email_verified"`
	Tags []string `json:"tags"`
	Lists []string `json:"lists"`
	CustomFields map[string]string `json:"custom_fields,omitempty"`
	LeadScore int `json:"lead_score,omitempty"`
	Source string `json:"source,omitempty"`
	EmailsSent int `json:"emails_sent"`
	EmailsOpened int `json:"emails_opened"`
	EmailsClicked int `json:"emails_clicked"`
	LastEmailAt string `json:"last_email_at,omitempty"`
	LastOpenAt string `json:"last_open_at,omitempty"`
	LastClickAt string `json:"last_click_at,omitempty"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}


// SDKCustomerInfo represents the SDKCustomerInfo type.
type SDKCustomerInfo struct {
	ID string `json:"id"`
	Email string `json:"email"`
	Name string `json:"name"`
	Phone string `json:"phone,omitempty"`
	StripeCustomerID string `json:"stripe_customer_id,omitempty"`
	Status string `json:"status"`
	TotalSpent int64 `json:"total_spent"`
	OrderCount int `json:"order_count"`
	SubscriptionCount int `json:"subscription_count"`
	CreatedAt string `json:"created_at"`
}


// SDKForgotPasswordRequest represents the SDKForgotPasswordRequest type.
type SDKForgotPasswordRequest struct {
	Email string `json:"email"`
}


// SDKLoginRequest represents the SDKLoginRequest type.
type SDKLoginRequest struct {
	Email string `json:"email"`
	Password string `json:"password"`
}


// SDKRefreshTokenRequest represents the SDKRefreshTokenRequest type.
type SDKRefreshTokenRequest struct {
	RefreshToken string `json:"refresh_token"`
}


// SDKRegisterRequest represents the SDKRegisterRequest type.
type SDKRegisterRequest struct {
	Email string `json:"email"`
	Password string `json:"password"`
	Name string `json:"name,omitempty"`
	PriceNickname string `json:"price_nickname,omitempty"`
	SuccessUrl string `json:"success_url,omitempty"`
	CancelUrl string `json:"cancel_url,omitempty"`
}


// SDKResetPasswordRequest represents the SDKResetPasswordRequest type.
type SDKResetPasswordRequest struct {
	Token string `json:"token"`
	Password string `json:"password"`
	ConfirmPassword string `json:"confirm_password"`
}


// SDKSiteSettings represents the SDKSiteSettings type.
type SDKSiteSettings struct {
	SiteName string `json:"site_name,omitempty"`
	Tagline string `json:"tagline,omitempty"`
	LogoUrl string `json:"logo_url,omitempty"`
	FaviconUrl string `json:"favicon_url,omitempty"`
	ContactEmail string `json:"contact_email,omitempty"`
	ContactPhone string `json:"contact_phone,omitempty"`
	ContactAddress string `json:"contact_address,omitempty"`
	SocialLinks map[string]string `json:"social_links,omitempty"`
	MetaTitleTemplate string `json:"meta_title_template,omitempty"`
	MetaDescription string `json:"meta_description,omitempty"`
	OgImageUrl string `json:"og_image_url,omitempty"`
}


// SDKUpdateCustomerRequest represents the SDKUpdateCustomerRequest type.
type SDKUpdateCustomerRequest struct {
	Name string `json:"name,omitempty"`
	Phone string `json:"phone,omitempty"`
	AvatarUrl string `json:"avatar_url,omitempty"`
	Status string `json:"status,omitempty"`
	Metadata string `json:"metadata,omitempty"`
}


// SDKVerifyEmailRequest represents the SDKVerifyEmailRequest type.
type SDKVerifyEmailRequest struct {
	Token string `json:"token"`
}


// SendEmailRequest represents the SendEmailRequest type.
type SendEmailRequest struct {
	To string `json:"to"`
	TemplateSlug string `json:"template_slug,omitempty"`
	Subject string `json:"subject,omitempty"`
	Body string `json:"body,omitempty"`
	TextBody string `json:"text_body,omitempty"`
	FromName string `json:"from_name,omitempty"`
	FromEmail string `json:"from_email,omitempty"`
	ReplyTo string `json:"reply_to,omitempty"`
	Variables map[string]string `json:"variables,omitempty"`
	Tags []string `json:"tags,omitempty"`
	Meta map[string]string `json:"meta,omitempty"`
}


// SendEmailResponse represents the SendEmailResponse type.
type SendEmailResponse struct {
	Success bool `json:"success"`
	MessageID string `json:"message_id"`
	Status string `json:"status"`
	Message string `json:"message,omitempty"`
}


// StatsOverviewResponse represents the StatsOverviewResponse type.
type StatsOverviewResponse struct {
	TotalContacts int `json:"total_contacts"`
	NewContacts int `json:"new_contacts"`
	ActiveContacts int `json:"active_contacts"`
	EmailsSent int `json:"emails_sent"`
	EmailsDelivered int `json:"emails_delivered"`
	EmailsOpened int `json:"emails_opened"`
	EmailsClicked int `json:"emails_clicked"`
	EmailsBounced int `json:"emails_bounced"`
	OpenRate float64 `json:"open_rate"`
	ClickRate float64 `json:"click_rate"`
	BounceRate float64 `json:"bounce_rate"`
	TotalRevenue int64 `json:"total_revenue"`
	OrderCount int `json:"order_count"`
	AvgOrderValue int64 `json:"avg_order_value"`
	NewSubscriptions int `json:"new_subscriptions"`
}


// SubscribeRequest represents the SubscribeRequest type.
type SubscribeRequest struct {
	Email string `json:"email"`
	Name string `json:"name,omitempty"`
}


// SubscriptionRequest represents the SubscriptionRequest type.
type SubscriptionRequest struct {
	CustomerID string `json:"customer_id"`
	PriceIds []string `json:"price_ids"`
}


// SubscriptionResponse represents the SubscriptionResponse type.
type SubscriptionResponse struct {
	ID string `json:"id"`
	StripeSubscriptionID string `json:"stripe_subscription_id"`
	Status string `json:"status"`
}


// TestWebhookResponse represents the TestWebhookResponse type.
type TestWebhookResponse struct {
	Success bool `json:"success"`
	StatusCode int `json:"status_code"`
	Response string `json:"response,omitempty"`
	Error string `json:"error,omitempty"`
}


// TrackClickRequest represents the TrackClickRequest type.
type TrackClickRequest struct {
	Token string `json:"token"`
	Url string `json:"url"`
}


// TrackConfirmRequest represents the TrackConfirmRequest type.
type TrackConfirmRequest struct {
	Token string `json:"token"`
}


// TrackConfirmResponse represents the TrackConfirmResponse type.
type TrackConfirmResponse struct {
	Success bool `json:"success"`
	Message string `json:"message,omitempty"`
	RedirectUrl string `json:"redirect_url,omitempty"`
}


// TrackOpenRequest represents the TrackOpenRequest type.
type TrackOpenRequest struct {
	Token string `json:"token"`
}


// TrackUnsubscribeRequest represents the TrackUnsubscribeRequest type.
type TrackUnsubscribeRequest struct {
	Token string `json:"token"`
}


// UnenrollSequenceRequest represents the UnenrollSequenceRequest type.
type UnenrollSequenceRequest struct {
	Email string `json:"email"`
	SequenceSlug string `json:"sequence_slug,omitempty"`
}


// UpdateContactRequest represents the UpdateContactRequest type.
type UpdateContactRequest struct {
	Name string `json:"name,omitempty"`
	Phone string `json:"phone,omitempty"`
	Company string `json:"company,omitempty"`
	CustomFields map[string]string `json:"custom_fields,omitempty"`
}


// UpdateWebhookRequest represents the UpdateWebhookRequest type.
type UpdateWebhookRequest struct {
	Url string `json:"url,omitempty"`
	Events []string `json:"events,omitempty"`
	Active bool `json:"active,omitempty"`
}


// UsageRequest represents the UsageRequest type.
type UsageRequest struct {
	SubscriptionItemID string `json:"subscription_item_id"`
	Quantity int `json:"quantity"`
}


// WorkshopAgendaDay represents the WorkshopAgendaDay type.
type WorkshopAgendaDay struct {
	Day string `json:"day"`
	Title string `json:"title"`
	Items []string `json:"items"`
}


// WorkshopEventInfo represents the WorkshopEventInfo type.
type WorkshopEventInfo struct {
	ID int64 `json:"id"`
	Slug string `json:"slug"`
	Title string `json:"title"`
	Description string `json:"description,omitempty"`
	StartDate string `json:"start_date"`
	EndDate string `json:"end_date"`
	StartTime string `json:"start_time"`
	EndTime string `json:"end_time"`
	Timezone string `json:"timezone"`
	LocationType string `json:"location_type"`
	LocationDetails string `json:"location_details,omitempty"`
	PriceCents int `json:"price_cents"`
	Currency string `json:"currency"`
	MaxSeats int `json:"max_seats"`
	SeatsRemaining int `json:"seats_remaining"`
	Status string `json:"status"`
	WhatsIncluded []string `json:"whats_included"`
	WhoItsFor []string `json:"who_its_for"`
	Agenda []WorkshopAgendaDay `json:"agenda"`
	ProductID string `json:"product_id,omitempty"`
	ProductSlug string `json:"product_slug,omitempty"`
	ProductName string `json:"product_name,omitempty"`
	AllowWaitlist bool `json:"allow_waitlist"`
	WaitlistLimit int `json:"waitlist_limit,omitempty"`
	WaitlistCount int `json:"waitlist_count,omitempty"`
	FunnelID int64 `json:"funnel_id,omitempty"`
	FunnelSlug string `json:"funnel_slug,omitempty"`
	ConfirmationSequenceID int64 `json:"confirmation_sequence_id,omitempty"`
	ReminderSequenceID int64 `json:"reminder_sequence_id,omitempty"`
	OrderBumpProductIds []string `json:"order_bump_product_ids,omitempty"`
}

